#version 450
// バインドレス（Descriptor Indexing）を使用するための拡張機能
#extension GL_EXT_nonuniform_qualifier : enable

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

// Renderer.cpp の PushConstants 構造体と一致させる
layout(push_constant) uniform PushConstants {
    uint outputImageIndex;
    uint sceneBufferIndex;
    uint resX;
    uint resY;
} pc;

// VulkanDevice.cpp のレイアウト定義に合わせる
// Binding 0: Storage Buffer の配列 (SceneData用)
struct SceneData {
    vec4 resolution;
    vec4 params;
    vec4 cameraPos;
};
layout(set = 0, binding = 0) buffer SceneDataBuffer {
    SceneData data;
} sceneBuffers[];

// Binding 1: Storage Image の配列 (画像出力用)
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D outputImages[];

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    
    vec2 uv = pixel_coords/vec2(pc.resX, pc.resY);

    vec3 col = vec3(1);

    col*=0.;

    if(uv.x < 0.5) col.x = 1.;
    if(uv.y > 0.5) col.y = 1.;

    // 画像へ書き込み (インデックス指定)
    // ここではデバッグ用に赤色を書き込み [cite: 4]
    imageStore(outputImages[pc.outputImageIndex], pixel_coords, vec4(col, 1.0));
}